// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: proto/battle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleService_BattleStream_FullMethodName = "/BattleService/BattleStream"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleServiceClient interface {
	BattleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PokemonUpdate, BattleStatus], error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) BattleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PokemonUpdate, BattleStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BattleService_ServiceDesc.Streams[0], BattleService_BattleStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PokemonUpdate, BattleStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_BattleStreamClient = grpc.BidiStreamingClient[PokemonUpdate, BattleStatus]

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility.
type BattleServiceServer interface {
	BattleStream(grpc.BidiStreamingServer[PokemonUpdate, BattleStatus]) error
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceServer struct{}

func (UnimplementedBattleServiceServer) BattleStream(grpc.BidiStreamingServer[PokemonUpdate, BattleStatus]) error {
	return status.Errorf(codes.Unimplemented, "method BattleStream not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}
func (UnimplementedBattleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	// If the following call pancis, it indicates UnimplementedBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_BattleStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BattleServiceServer).BattleStream(&grpc.GenericServerStream[PokemonUpdate, BattleStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_BattleStreamServer = grpc.BidiStreamingServer[PokemonUpdate, BattleStatus]

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BattleStream",
			Handler:       _BattleService_BattleStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/battle.proto",
}
